add load_forecasts_zoltar() function
Infectious-Disease-Modeling-Hubs/hubData pull request #36
Opened 2024-06-11 17:41 UTC by matthewcornell

closes [create a zoltar option in connect_hub() #10]

2024-06-12 15:09 UTC, bsweger reviewed
Very excited to see `hubData` expanded to include a Zoltar connection!

I had one inline comment about the function name. Also noting that I was able to use the function successfully as documented, but got a 503 when connecting to a large hub and grabbing everything.

```
> df <- load_forecasts_zoltar("ECDC European COVID-19 Forecast Hub")
[snip]
get_resource(): GET: https://zoltardata.com/api/job/616053/
QUEUED
get_resource(): GET: https://zoltardata.com/api/job/616053/
QUEUED
get_resource(): GET: https://zoltardata.com/api/job/616053/
SUCCESS
get_resource(): GET: https://zoltardata.com/api/job/616053/data/
Error in get_resource(zoltar_connection, data_url, col_types) : 
  Service Unavailable (HTTP 503).
```

2024-06-12 15:09 UTC, bsweger commented on R/load_forecasts_zoltar.R
What do you think about giving this function a name that more closely matches the existing `hubData` interface (_e.g._, `connect_hub_zoltar`, `connect_zoltar`, `connect_model_output_zoltar`)?

2024-06-12 15:10 UTC, nickreich requested changes
I have not reviewed the code in detail but @matthewcornell asked for input on documentation. I reviewed the [netlify documentation preview of the load_forecasts_zoltar() function](https://6669a93550c0d7349aaaf9b7--hubdata-pr-preview.netlify.app/reference/load_forecasts_zoltar) and have a few minor suggestions/comments.

1. The details section of the page looks like it is supposed to render as a list but instead it just reads as one paragraph. This should be edited so it renders as a list
2. Add a bit more info (2-3 sentences) about what Zoltar is in the documentation. A hubverse user might have no idea what Zoltar is, so we need to tell them what it is, where it lives (adding an actual link, not just text). I'm thinking...
3. In addition to a general introduction, include a few details about how zoltar concepts map to hubverse concepts, like how "units" and "targets" are like "task-id" variables. and "timezero" is a round id? or something like that.
4. add a link/reference to zoltr, so people could understand how to interact with and extract data from that tool.
5. I think it should be clearer in the documentation that **you need a Zoltar account for this function to work for you**. Right now, this is stated kind of implicitly in the details when talking about environment variables.

In terms of adding an example of this code to the vignette, I this this is not necessary for this PR because it adds complexity (e.g. storing secrets) and won't be reproducible for users without Zoltar accounts. But I will say that I large advantage of this function is how it will make the covid-19 forecast hub data directly available in hubverse format, and maybe giving a demo of that could be useful somewhere at some point. Maybe worth filing an issue here, or in the main hubverse repo, at some point about that.

2024-06-12 15:39 UTC, matthewcornell commented on R/load_forecasts_zoltar.R
Re: 503, yes, it will time out if you ask for a "large" number of forecasts. That particular project has ~1/2M predictions, each of which has ~20 data rows, for ~10M rows. I believe the workers that handle queries are limited to a 7 minute runtime before they're shut down.

Re: the function name, I'll leave it to others to decide (@nickreich , @lshandross , @annakrystalli  ?)

2024-06-12 15:57 UTC, lshandross commented on R/load_forecasts_zoltar.R
I'm happy with either of the first two names (the last one feels too wordy)

2024-06-12 19:38 UTC, matthewcornell commented
@nickreich and @bsweger , @lshandross and I have updated the code to incorporate your helpful comments. We renamed the function and updated its docs. Please take a look - the [netlify preview](https://6669f8753bf1502267f2b365--hubdata-pr-preview.netlify.app/reference/collect_zoltar_forecasts) shows the final function documentation.

2024-06-13 08:47 UTC, annakrystalli commented
Final points:
- [ ] The version needs to be bumped in the `DESCRIPTION` file
- [ ] An item introducing the new feature needs to be added in `NEWS.md`

2024-06-13 08:48 UTC, annakrystalli requested changes

2024-06-13 08:48 UTC, annakrystalli commented on R/collect_zoltar_forecasts.R
> +    purrr::map_dfr(.f = function(split_outputs) {
Note that `map_dfr()` has [been superceded in `purrr` in favour of `map() |> purrr::list_rbind()`](https://purrr.tidyverse.org/reference/map_dfr.html)

2024-06-13 08:48 UTC, annakrystalli commented on R/collect_zoltar_forecasts.R
> +#' @param project_name a string naming the Zoltar project to load forecasts from. assumes the host is zoltardata.com
General comment on the documentation. It should have proper sentence format (i.e. capitals after periods, not all lower case)

2024-06-13 08:48 UTC, annakrystalli commented on R/collect_zoltar_forecasts.R
> +#'   caution. defaults to NULL to load the latest version
Why not make things easier by requiring that users provide character strings of dates in ISO format only? You can then check that its valid and then safely convert to a format zoltar will accept? Makes it simpler to document too. 

If not, given you are using `strftime(as_of, format = "%Y-%m-%d %H:%M:%S", tz = "UTC", usetz = TRUE)` to check whether the input is valid, it's better to point to that as the expectation in the docs rather to a python package as that's what's actually going to trigger the failure.

2024-06-13 08:48 UTC, annakrystalli commented on R/collect_zoltar_forecasts.R
> +  zoltr::zoltar_authenticate(zoltar_connection, Sys.getenv("Z_USERNAME"), Sys.getenv("Z_PASSWORD"))
Is there any useful metadata made available through a zoltar connection or computational efficiency (if we wanted to make multliple subsequent but different queries to a project) to be gained from having the above two steps separated into a `connect_zoltar()` function?

2024-06-13 08:48 UTC, annakrystalli commented on R/collect_zoltar_forecasts.R
> +    dplyr::filter(.data$numeric_value, .data$numeric_sample, !class %in% c("named", "mode")) |>
Although the tests pass, am noticng a bunch of warning in the output re deprecation of `.data$` in tidyselect since 1.2.0, e.g. 
https://github.com/Infectious-Disease-Modeling-Hubs/hubData/actions/runs/9488629904/job/26147999504?pr=36#step:6:161

This will likely affect other code in this package and other packages as well but it's probably good to understand what the up to date way of using tidy select is and start applying it throughout our packages.  Found this[ blogpost which seems useful](https://www.tidyverse.org/blog/2022/10/tidyselect-1-2-0/). Looks like we need to use different approaches in selecting situations vs data masking (e.g. mutating) situations.

2024-06-13 08:48 UTC, annakrystalli commented on R/collect_zoltar_forecasts.R
> +    dplyr::filter(.data$numeric_value, .data$numeric_sample, !class %in% c("named", "mode")) |>
Also, for simple stuff like selecting a couple of columns, it's easier to use base R.

2024-06-13 08:48 UTC, annakrystalli commented on R/load_forecasts_zoltar.R
I would actually advocate for `collect_zoltar()` for more consistency with `collect_hub()` and more conciseness (if that's even a word !)

2024-06-13 12:53 UTC, matthewcornell commented
@nickreich said:
> It probably is worth updating CRAN. 0.5.1 on CRAN vs. 1.0.1 on GitHub.

2024-06-13 13:04 UTC, nickreich reviewed
I second @annakrystalli 's stylistic requests for the documentation (sentence capitalization, function re-naming, etc...), but my documentation-content related concerns from my first review have been addressed very nicely with the additional descriptive/background/informational text in the documentation. thank you!

2024-06-13 13:34 UTC, bsweger commented on R/load_forecasts_zoltar.R
> Re: 503, yes, it will time out if you ask for a "large" number of forecasts. That particular project has ~1/2M predictions, each of which has ~20 data rows, for ~10M rows. I believe the workers that handle queries are limited to a 7 minute runtime before they're shut down. You could try a more constrained query, such as models, timezeros, or units.
> 

Got it! Then I would vote for catching 5xx HTTP errors and returning a user-friendly message about trying the connection again with more specific filters.

2024-06-13 13:47 UTC, matthewcornell commented on R/load_forecasts_zoltar.R
> I would actually advocate for `collect_zoltar()` for more consistency with `collect_hub()` and more conciseness (if that's even a word !)

Thanks for the suggestion, Anna. We included "forecasts" in the function name because we wanted to differentiate between querying zoltar forecasts (which this function does) and querying truth (possibly in a separate function in the future).

2024-06-13 14:10 UTC, annakrystalli commented on R/load_forecasts_zoltar.R
I see. In `collect_hub()` we are also only accessing model output data though so it still fits the design pattern. When we decide if and how target data will be accessed we can try and mirror the approach?

2024-06-13 15:25 UTC, matthewcornell commented
Thanks for the comments, Anna! Here's what we decided:
- re: the ".data$" warnings: we changed our two dplyr::select() calls to use base R, but we still have warnings from other dplyr calls. We aren't sure how to proceed in getting rid of those remaining warnings.
- re: ISO format: Thanks for the suggestion. We decided to keep the current code rather than dive deep into new formatting, but we included information about the actual R function used, as you suggested.
- re: Is there any useful metadata: Good idea. I'll make an issue for it.
- re: showing actual query results: ""

2024-06-13 16:35 UTC, annakrystalli commented on R/collect_zoltar_forecasts.R
> +    dplyr::filter(.data$numeric_value, .data$numeric_sample, !class %in% c("named", "mode")) |>
I think this is a wider `dplyr` style guide we'll need to sit out and work out all together and start applying across our packages as the new way seems to be less intuitive initially and needs working through.

2024-06-13 16:39 UTC, annakrystalli commented
Thanks for the updates @matthewcornell and @lshandross !
Most of my comments have been addressed.

I still feel `collect_zoltar()` is best in terms of function name (see here: https://github.com/Infectious-Disease-Modeling-Hubs/hubData/pull/36#discussion_r1638291425)

I've also made a suggested change to set a minimum `zoltr` version in `DESCRIPTION` given earlier versions don't export the required function.

2024-06-13 16:42 UTC, annakrystalli approved these changes

2024-06-13 17:10 UTC, bsweger approved these changes
This comment got lost in a thread about function names, but if we know in advance that this feature won't work when querying large volumes of data from Zoltar, it would be more polished if we caught that HTTP 503 and returned a more user-friendly message advising people to add additional filters/constraints to their request.

That could be a follow-up, however. Great to have this foundational layer in!

2024-06-13 18:50 UTC, nickreich approved these changes
Great work on this! Excited to have this functionality in the package.

2024-06-13 18:50 UTC, merged